### ISSUE TITLE
Not Work, need Net 6.0

### ISSUE THREAD

**Issue by ArtZero1** [Zenixas/NetRenamer#1]
Please build for .Net 3.5 and .Net 4.8

Thank you..

**Comment by Zenixas** [comment]
Hello, I've added a branch for Net Framework 4.8:
https://github.com/Zenixas/NetRenamer/tree/NetFramework
And also the release
https://github.com/Zenixas/NetRenamer/releases/tag/1.0

The menu looks a bit iffy when changed the version, but overall works well.
